n = input('Digite algo:')
print('Tipo primitivo?'type(algo))
print('Só tem espaços?'.isspace())
print('É um número?'.isnumeric())
print('É alfabético?'.isalpha())
print('É alfanumérico?'.isalnum())
print('Esta em maiúsculas?'.isupper())
print('Esta em minúsculas?'.islower())
print('Esta capitalizada?'.istitle())